### ISSUE TITLE
Bad bash PATH

### ISSUE THREAD

**Issue by rdesniol** [kermith72/auto_install#12]
Dear kermith,
First thanks for all the job you have done around centreon 
I found a small bug using your script centreon_central_2004.sh under a container using the image debian:lastest (10.6)
The line 1026 uses /usr/bin/bash which does not exist in this debian container but /bin/bash does.
In this image the link /bin => usr/bin does not exist.
That is it. ;-))

**Comment by kermith72** [comment]
I fixed with version 1.56
