### ISSUE TITLE
Apache on poller

### ISSUE THREAD

**Issue by Justice81** [kermith72/auto_install#4]
Hi,

is apache2 really needed on a poller? The is no web interface

https://github.com/kermith72/auto_install/blob/c128a88881c19190e9c304a05705b82b4607866a/debian10/centreon_poller_1910.sh#L505

**Comment by kermith72** [comment]
Currently the source version requires the installation of apache. But it is possible to uninstall apache after installation without disrupting operation.

> apt-get remove apache2
apt-get auto-remove
