### ISSUE TITLE
Update Version

### ISSUE THREAD

**Issue by Justice81** [kermith72/auto_install#7]
trying to update an install from december 2019

Step1  => repo non-free on Buster Install                       [ OK ]
./centreon_central_1910.sh: line 1219: ((: 10#0[0] > 10#0: syntax error: invalid arithmetic operator (error token is "[0] > 10#0")
./centreon_central_1910.sh: line 1223: ((: 10#0[0] < 10#0: syntax error: invalid arithmetic operator (error token is "[0] < 10#0")
Step3  => Clib already installed                                [ OK ]
./centreon_central_1910.sh: line 1219: ((: 10#1[0] > 10#0: syntax error: invalid arithmetic operator (error token is "[0] > 10#0")
./centreon_central_1910.sh: line 1223: ((: 10#1[0] < 10#0: syntax error: invalid arithmetic operator (error token is "[0] < 10#0")
Step4  => Centreon Perl and SSH connectors already installed    [ OK ]
./centreon_central_1910.sh: line 1219: ((: 10#13[0] > 10#7: syntax error: invalid arithmetic operator (error token is "[0] > 10#7")
./centreon_central_1910.sh: line 1223: ((: 10#13[0] < 10#7: syntax error: invalid arithmetic operator (error token is "[0] < 10#7")
Step5  => Centreon Engine already installed                     [ OK ]
Step6  => Monitoring plugins already installed                  [ OK ]
./centreon_central_1910.sh: line 1219: ((: 10#20200204[0] > 10#20191016: syntax error: invalid arithmetic operator (error token is "[0] > 10#20191016")
./centreon_central_1910.sh: line 1223: ((: 10#20200204[0] < 10#20191016: syntax error: invalid arithmetic operator (error token is "[0] < 10#20191016")
Step7  => Centreon plugins already installed                    [ OK ]
./centreon_central_1910.sh: line 1219: ((: 10#3[0] > 10#1: syntax error: invalid arithmetic operator (error token is "[0] > 10#1")
./centreon_central_1910.sh: line 1223: ((: 10#3[0] < 10#1: syntax error: invalid arithmetic operator (error token is "[0] < 10#1")
Step8  => Centreon Broker already installed                     [ OK ]
./centreon_central_1910.sh: line 1219: ((: 10#10[0] > 10#3: syntax error: invalid arithmetic operator (error token is "[0] > 10#3")
./centreon_central_1910.sh: line 1223: ((: 10#10[0] < 10#3: syntax error: invalid arithmetic operator (error token is "[0] < 10#3")
Step9  => Php-fpm already installed                             [ OK ]
./centreon_central_1910.sh: line 1219: ((: 10#10[0] > 10#3: syntax error: invalid arithmetic operator (error token is "[0] > 10#3")
./centreon_central_1910.sh: line 1223: ((: 10#10[0] < 10#3: syntax error: invalid arithmetic operator (error token is "[0] < 10#3")
Step10  => Centreon template already installed                   [ OK ]
./centreon_central_1910.sh: line 1219: ((: 10#10[0] > 10#3: syntax error: invalid arithmetic operator (error token is "[0] > 10#3")
./centreon_central_1910.sh: line 1223: ((: 10#10[0] < 10#3: syntax error: invalid arithmetic operator (error token is "[0] < 10#3")
Step11  => Centreon web already installed                   [ OK ]

**Comment by kermith72** [comment]
Update mode does not work. moreover, I have problems with the update 19.10 to 20.04
see https://github.com/centreon/centreon/issues/8698

**Comment by Justice81** [comment]
Just trying to update to the latest 1910 version

**Comment by kermith72** [comment]
ok, I'm working on this version, soon

**Comment by kermith72** [comment]
It's fixed, I completely redid the script. See the explanation on my site
https://www.sugarbug.fr/blog/files/script-auto-maj.html
 Sorry in french

**Comment by Justice81** [comment]
Thank you.
Works good in our test environment.

> Sorry in french
google chrome translator works :-)
