### ISSUE TITLE
Wrong text

### ISSUE THREAD

**Issue by Justice81** [kermith72/auto_install#8]
https://github.com/kermith72/auto_install/blob/79fcf622b9a442871e304a0592d8b5883157320a/debian10/centreon_central_1910.sh#L1009

https://github.com/kermith72/auto_install/blob/79fcf622b9a442871e304a0592d8b5883157320a/debian10/centreon_central_1910.sh#L1024

should be ================| Centreon **Poller** Install details $VERSION_BATCH |============

same in centreon_poller_2004.sh

Raspian and 1904 are good

**Comment by kermith72** [comment]
Thanks @Justice81 it's OK.
