### ISSUE TITLE
problem at Update

### ISSUE THREAD

**Issue by Justice81** [kermith72/auto_install#9]
https://github.com/kermith72/auto_install/blob/dc3039ba7f2074cf38fe317adb3977c67b862db0/debian10/centreon_central_1910.sh#L864

We updated our production system today.
Had the following error:

./centreon_central_1910.sh: line 864: /usr/bin/rm: Argument list too long

in /var/lib/centreon/sessions where more than 200k files

maybe another command for deleting helps. we did it with "for i in * ; do rm $i ; done"
But took a long time

**Comment by kermith72** [comment]
Script modified and verified, thank
